In [1]:
!pip install numpy


[notice] A new release of pip available: 22.2.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [4]:
np

<module 'numpy' from 'c:\\Users\\kamak\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
lst=[[1,2,3],[2,3,4],[6,7,8]]
print(lst)
print(type(lst))

[[1, 2, 3], [2, 3, 4], [6, 7, 8]]
<class 'list'>


In [9]:
arr=np.array(lst)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)



[[1 2 3]
 [2 3 4]
 [6 7 8]]
2
(3, 3)
9
int64


In [10]:
o=np.ones((4,6))
print(o)
print(type(o))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [26]:
k=np.random.random((3,3))
k

array([[0.66063782, 0.05792062, 0.9357216 ],
       [0.23381545, 0.3244294 , 0.32733618],
       [0.00490063, 0.92633742, 0.09662146]])

In [11]:
if np.random.random() >0.6:
    print("Run the function")
else:
    print("Dont ruin the function")

Dont ruin the function


In [13]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [15]:
np.linspace(1,10,49) #this are with equidistance


array([ 1.    ,  1.1875,  1.375 ,  1.5625,  1.75  ,  1.9375,  2.125 ,
        2.3125,  2.5   ,  2.6875,  2.875 ,  3.0625,  3.25  ,  3.4375,
        3.625 ,  3.8125,  4.    ,  4.1875,  4.375 ,  4.5625,  4.75  ,
        4.9375,  5.125 ,  5.3125,  5.5   ,  5.6875,  5.875 ,  6.0625,
        6.25  ,  6.4375,  6.625 ,  6.8125,  7.    ,  7.1875,  7.375 ,
        7.5625,  7.75  ,  7.9375,  8.125 ,  8.3125,  8.5   ,  8.6875,
        8.875 ,  9.0625,  9.25  ,  9.4375,  9.625 ,  9.8125, 10.    ])

In [47]:
j=np.random.random((3,2))
j

array([[0.67675293, 0.218945  ],
       [0.82400337, 0.85047493],
       [0.17789831, 0.38521529]])

In [49]:
k=np.reshape(j,(1,6))
k

array([[0.67675293, 0.218945  , 0.82400337, 0.85047493, 0.17789831,
        0.38521529]])

In [51]:
k.flatten() # to flatten convert multi dimensional array to noe dimensional

array([0.67675293, 0.218945  , 0.82400337, 0.85047493, 0.17789831,
       0.38521529])

In [2]:
import numpy as sud
arr=sud.array([i for i in range(1,7)] +[ j for j in range(2,5)])
arr

array([1, 2, 3, 4, 5, 6, 2, 3, 4])

In [81]:
print(arr+1,sep=",")
print(arr*2)
print(arr/2)
print(arr*5)
print(arr**3)



[2 3 4 5 6 7 3 4 5]
[ 2  4  6  8 10 12  4  6  8]
[0.5 1.  1.5 2.  2.5 3.  1.  1.5 2. ]
[ 5 10 15 20 25 30 10 15 20]
[  1   8  27  64 125 216   8  27  64]


In [18]:
print(arr.max())
arr.min()

6


np.int64(1)

In [3]:
a=[[1,23,3],[6,7,5],[6,2,4]]
p=sud.array(a)
p
print(p.max(axis=1))
print(p.min(axis=1))
print(p.sum(axis=1))

[23  7  6]
[1 5 2]
[27 18 12]


In [157]:
import numpy as nu
arr=nu.array([[1,2,4],[3,5,6],[9,7,5]])
print("a = ",arr)
arr1=nu.array([[9,8,7],[4,5,3],[7,5,2]])
print(" b =",arr1)
arr1+arr

a =  [[1 2 4]
 [3 5 6]
 [9 7 5]]
 b = [[9 8 7]
 [4 5 3]
 [7 5 2]]


array([[10, 10, 11],
       [ 7, 10,  9],
       [16, 12,  7]])

In [101]:
arr1*arr
arr-arr1
arr1.dot(arr)

array([[ 96, 107, 119],
       [ 46,  54,  61],
       [ 40,  53,  68]])

In [25]:
s=sud.array([i for i in range(1,6)])
s


array([1, 2, 3, 4, 5])

In [26]:
s[-2:-3]
arr

array([1, 2, 3, 4, 5, 6, 2, 3, 4])

In [137]:
arr[:1,:1]

array([[1]])

In [149]:
import numpy as np
ar=np.array([[1,2,3,32],[5,3,576,2],[1,2,3,4]])

d=np.array([np.arange(1,30,3)])
np.sort(d,axis=1,kind='mergesort')

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28]])

In [37]:
import numpy as df
arr=df.array([df.arange(1,30,2)])

print(arr)

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]]


In [34]:
arr
i=df.sort(arr,axis=1,kind='mergesort')
df.sort(arr,axis=0,kind='mergesort')
print(i)


[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]]


In [36]:
arr1=df.array([[1,2,3,4],[5,6,7,8]])
arr2=df.array([[8,7,6,5],[4,3,2,1]])
print(arr1,"\n\n",arr2)

[[1 2 3 4]
 [5 6 7 8]] 

 [[8 7 6 5]
 [4 3 2 1]]


In [35]:
df.vstack((arr1,arr2))
df.vstack((arr2,arr1))
df.hstack((arr1,arr2))
df.concatenate((arr1,arr2),axis=1)
df.concatenate((arr1,arr2),axis=0)
df.vstack((arr2,arr1))

NameError: name 'arr1' is not defined

In [206]:
df.split(arr1,2)
df.hsplit(arr1,2)
df.vsplit(arr1,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [207]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [222]:
import numpy as fb
k=fb.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print(k)
l=fb.array([i for i in range(0,9)])
print(l)
k=fb.array([i for i in range(0,11)])
l[2:6]
l[3:-3]
k[:1 ,: ]

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
[0 1 2 3 4 5 6 7 8]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [237]:
import numpy as np
lst=[ i for i in range(0,11)]
l=0
for i in lst:
    if(i>5):
        l=l+1
    
print(l)
arr1
list(arr1)
list.arr


5


[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [232]:
kst=np.array(lst)
kst[kst>5]
len(kst)
(kst[kst % 5==0])
print(kst[kst % 5==1])
list()


[1 6]


In [275]:
c=np.array([[1,2,3,4,5],[20,30,40,50,60]])
d=np.array([[6,7,8,9,10],[9,8,7,6,5]])
d=np.column_stack([c,d])
print(d)

[[ 1  2  3  4  5  6  7  8  9 10]
 [20 30 40 50 60  9  8  7  6  5]]


In [269]:
c=np.array([1,2,3,5,4,6,7,8,5,3,2])
c
print(c[1::2])
print(c[1:2])
print(c[::2])
print(c[1:1])

[2 5 6 8 3]
[2]
[1 3 4 7 5 2]
[]
